server:
  port: 9001
  tomcat:
    connection-timeout: 2s # ????? ????? ????????? TCP-?????????? ?? ??????? ? ??????????? ?????????? HTTP-???????
    keep-alive-timeout: 15s # ????????????????? ???????? ?????????? ??? ???????? ????? HTTP-????????
    threads:
      max: 50 # ???????????? ?????????? ???????, ??????? ????? ???????? ????????????
      min-spare: 5 # ??????????? ?????????? ???????, ??????? ?????? ?????? ????????

polar:
  greeting: Welcome to the local book catalog!